#BeginMacro(SobraAguaMia)
  if((1,0,0) = -1, 
     (0,0,0), 
     if(((0,0,0) - 4 + (1,0,0))>=0, (0,0,0) - 4 + (1,0,0), 0)) 
#EndMacro

#BeginMacro(SobraAguaN)
  if((1,-1,0) = -1, 
     (0,-1,0), 
     if(((0,-1,0) - 4 + (1,-1,0))>=0, (0,-1,0) - 4 + (1,-1,0), 0)) 
#EndMacro

#BeginMacro(SobraAguaNE)
  if((1,-1,1) = -1, 
     (0,-1,1), 
     if(((0,-1,1) - 4 + (1,-1,1))>=0, (0,-1,1) - 4 + (1,-1,1), 0)) 
#EndMacro

#BeginMacro(SobraAguaE)
  if((1,0,1) = -1, 
     (0,0,1), 
     if(((0,0,1) - 4 + (1,0,1))>=0, (0,0,1) - 4 + (1,0,1), 0)) 
#EndMacro

#BeginMacro(SobraAguaSE)
  if((1,1,1) = -1, 
     (0,1,1), 
     if(((0,1,1) - 4 + (1,1,1))>=0, (0,1,1) - 4 + (1,1,1), 0)) 
#EndMacro

#BeginMacro(SobraAguaS)
  if((1,1,0) = -1, 
     (0,1,0), 
     if(((0,1,0) - 4 + (1,1,0))>=0, (0,1,0) - 4 + (1,1,0), 0)) 
#EndMacro

#BeginMacro(SobraAguaSO)
  if((1,1,-1) = -1, 
     (0,1,-1), 
     if(((0,1,-1) - 4 + (1,1,-1))>=0, (0,1,-1) - 4 + (1,1,-1), 0)) 
#EndMacro

#BeginMacro(SobraAguaO)
  if((1,0,-1) = -1, 
     (0,0,-1), 
     if(((0,0,-1) - 4 + (1,0,-1))>=0, (0,0,-1) - 4 + (1,0,-1), 0)) 
#EndMacro

#BeginMacro(SobraAguaNO)
  if((1,-1,-1) = -1, 
     (0,-1,-1), 
     if(((0,-1,-1) - 4 + (1,-1,-1))>=0, (0,-1,-1) - 4 + (1,-1,-1), 0)) 
#EndMacro
